service: sls-custom-authorizer

provider:
  name: aws
  runtime: nodejs4.3
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  region: ap-northeast-1

custom:
  defaultStage: dev
  profiles:
    dev: devSls
    prod: prodSls

package:
  exclude:
    - .git/**
    - README.md

functions:
  authorizerFunc:
    handler: authorizer.authorizer

  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
          authorizer: authorizerFunc
